name: rag-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - faiss-cpu
  - scikit-learn
  - pandas
  - matplotlib
  - jupyter
  - pip:
      - langgraph
      - langchain
      - ragas
      - openai
      - sentence-transformers
      - python-dotenv
